module Sfizio
  require "sfizio/command"
  require "sfizio/brewfile/brewfile"
  require "sfizio/brewfile/DSL"
  require "sfizio/core/formula"
  require "sfizio/core/tap"
  require "sfizio/core/config"
  require "sfizio/install/installer"
  require "sfizio/clean/clean"

  require "sfizio/brew_cli/tap_info"
  require "sfizio/brew_cli/tap_new"
  require "sfizio/brew_cli/link"
  require "sfizio/brew_cli/info"
  require "sfizio/brew_cli/install"
  require "sfizio/brew_cli/extract"
  require "sfizio/brew_cli/update"
  require "sfizio/brew_cli/tap"
  require "sfizio/brew_cli/uninstall"
end
